/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as NodesRouteRouteImport } from './routes/nodes/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as SettingsSubscriptionsRouteImport } from './routes/settings/subscriptions'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsMonitoringRouteImport } from './routes/settings/monitoring'
import { Route as SettingsManagementApiRouteImport } from './routes/settings/management-api'
import { Route as SettingsDatabaseRouteImport } from './routes/settings/database'
import { Route as NodesNewRouteImport } from './routes/nodes/new'
import { Route as NodesNodeIdRouteImport } from './routes/nodes/$nodeId'
import { Route as SettingsEmailsRouteRouteImport } from './routes/settings/emails/route'
import { Route as SettingsEmailsIndexRouteImport } from './routes/settings/emails/index'
import { Route as SettingsEmailsNewRouteImport } from './routes/settings/emails/new'
import { Route as SettingsEmailsSendoutIdRouteImport } from './routes/settings/emails/$sendoutId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRouteRoute = NodesRouteRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRouteRoute,
} as any)
const SettingsSubscriptionsRoute = SettingsSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsMonitoringRoute = SettingsMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsManagementApiRoute = SettingsManagementApiRouteImport.update({
  id: '/management-api',
  path: '/management-api',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDatabaseRoute = SettingsDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const NodesNewRoute = NodesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NodesRouteRoute,
} as any)
const NodesNodeIdRoute = NodesNodeIdRouteImport.update({
  id: '/$nodeId',
  path: '/$nodeId',
  getParentRoute: () => NodesRouteRoute,
} as any)
const SettingsEmailsRouteRoute = SettingsEmailsRouteRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsEmailsIndexRoute = SettingsEmailsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsEmailsRouteRoute,
} as any)
const SettingsEmailsNewRoute = SettingsEmailsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SettingsEmailsRouteRoute,
} as any)
const SettingsEmailsSendoutIdRoute = SettingsEmailsSendoutIdRouteImport.update({
  id: '/$sendoutId',
  path: '/$sendoutId',
  getParentRoute: () => SettingsEmailsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nodes': typeof NodesRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/settings/emails': typeof SettingsEmailsRouteRouteWithChildren
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/nodes/new': typeof NodesNewRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/management-api': typeof SettingsManagementApiRoute
  '/settings/monitoring': typeof SettingsMonitoringRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/subscriptions': typeof SettingsSubscriptionsRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/settings/emails/$sendoutId': typeof SettingsEmailsSendoutIdRoute
  '/settings/emails/new': typeof SettingsEmailsNewRoute
  '/settings/emails/': typeof SettingsEmailsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nodes': typeof NodesRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/nodes/new': typeof NodesNewRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/management-api': typeof SettingsManagementApiRoute
  '/settings/monitoring': typeof SettingsMonitoringRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/subscriptions': typeof SettingsSubscriptionsRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/settings': typeof SettingsIndexRoute
  '/users': typeof UsersIndexRoute
  '/settings/emails/$sendoutId': typeof SettingsEmailsSendoutIdRoute
  '/settings/emails/new': typeof SettingsEmailsNewRoute
  '/settings/emails': typeof SettingsEmailsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nodes': typeof NodesRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/settings/emails': typeof SettingsEmailsRouteRouteWithChildren
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/nodes/new': typeof NodesNewRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/management-api': typeof SettingsManagementApiRoute
  '/settings/monitoring': typeof SettingsMonitoringRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/subscriptions': typeof SettingsSubscriptionsRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/settings/emails/$sendoutId': typeof SettingsEmailsSendoutIdRoute
  '/settings/emails/new': typeof SettingsEmailsNewRoute
  '/settings/emails/': typeof SettingsEmailsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nodes'
    | '/settings'
    | '/users'
    | '/analytics'
    | '/forgot-password'
    | '/invitations'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/settings/emails'
    | '/nodes/$nodeId'
    | '/nodes/new'
    | '/settings/database'
    | '/settings/management-api'
    | '/settings/monitoring'
    | '/settings/notifications'
    | '/settings/subscriptions'
    | '/users/$userId'
    | '/settings/'
    | '/users/'
    | '/settings/emails/$sendoutId'
    | '/settings/emails/new'
    | '/settings/emails/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nodes'
    | '/analytics'
    | '/forgot-password'
    | '/invitations'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/nodes/$nodeId'
    | '/nodes/new'
    | '/settings/database'
    | '/settings/management-api'
    | '/settings/monitoring'
    | '/settings/notifications'
    | '/settings/subscriptions'
    | '/users/$userId'
    | '/settings'
    | '/users'
    | '/settings/emails/$sendoutId'
    | '/settings/emails/new'
    | '/settings/emails'
  id:
    | '__root__'
    | '/'
    | '/nodes'
    | '/settings'
    | '/users'
    | '/analytics'
    | '/forgot-password'
    | '/invitations'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/settings/emails'
    | '/nodes/$nodeId'
    | '/nodes/new'
    | '/settings/database'
    | '/settings/management-api'
    | '/settings/monitoring'
    | '/settings/notifications'
    | '/settings/subscriptions'
    | '/users/$userId'
    | '/settings/'
    | '/users/'
    | '/settings/emails/$sendoutId'
    | '/settings/emails/new'
    | '/settings/emails/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NodesRouteRoute: typeof NodesRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvitationsRoute: typeof InvitationsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/settings/subscriptions': {
      id: '/settings/subscriptions'
      path: '/subscriptions'
      fullPath: '/settings/subscriptions'
      preLoaderRoute: typeof SettingsSubscriptionsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/monitoring': {
      id: '/settings/monitoring'
      path: '/monitoring'
      fullPath: '/settings/monitoring'
      preLoaderRoute: typeof SettingsMonitoringRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/management-api': {
      id: '/settings/management-api'
      path: '/management-api'
      fullPath: '/settings/management-api'
      preLoaderRoute: typeof SettingsManagementApiRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/database': {
      id: '/settings/database'
      path: '/database'
      fullPath: '/settings/database'
      preLoaderRoute: typeof SettingsDatabaseRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/nodes/new': {
      id: '/nodes/new'
      path: '/new'
      fullPath: '/nodes/new'
      preLoaderRoute: typeof NodesNewRouteImport
      parentRoute: typeof NodesRouteRoute
    }
    '/nodes/$nodeId': {
      id: '/nodes/$nodeId'
      path: '/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof NodesNodeIdRouteImport
      parentRoute: typeof NodesRouteRoute
    }
    '/settings/emails': {
      id: '/settings/emails'
      path: '/emails'
      fullPath: '/settings/emails'
      preLoaderRoute: typeof SettingsEmailsRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/emails/': {
      id: '/settings/emails/'
      path: '/'
      fullPath: '/settings/emails/'
      preLoaderRoute: typeof SettingsEmailsIndexRouteImport
      parentRoute: typeof SettingsEmailsRouteRoute
    }
    '/settings/emails/new': {
      id: '/settings/emails/new'
      path: '/new'
      fullPath: '/settings/emails/new'
      preLoaderRoute: typeof SettingsEmailsNewRouteImport
      parentRoute: typeof SettingsEmailsRouteRoute
    }
    '/settings/emails/$sendoutId': {
      id: '/settings/emails/$sendoutId'
      path: '/$sendoutId'
      fullPath: '/settings/emails/$sendoutId'
      preLoaderRoute: typeof SettingsEmailsSendoutIdRouteImport
      parentRoute: typeof SettingsEmailsRouteRoute
    }
  }
}

interface NodesRouteRouteChildren {
  NodesNodeIdRoute: typeof NodesNodeIdRoute
  NodesNewRoute: typeof NodesNewRoute
}

const NodesRouteRouteChildren: NodesRouteRouteChildren = {
  NodesNodeIdRoute: NodesNodeIdRoute,
  NodesNewRoute: NodesNewRoute,
}

const NodesRouteRouteWithChildren = NodesRouteRoute._addFileChildren(
  NodesRouteRouteChildren,
)

interface SettingsEmailsRouteRouteChildren {
  SettingsEmailsSendoutIdRoute: typeof SettingsEmailsSendoutIdRoute
  SettingsEmailsNewRoute: typeof SettingsEmailsNewRoute
  SettingsEmailsIndexRoute: typeof SettingsEmailsIndexRoute
}

const SettingsEmailsRouteRouteChildren: SettingsEmailsRouteRouteChildren = {
  SettingsEmailsSendoutIdRoute: SettingsEmailsSendoutIdRoute,
  SettingsEmailsNewRoute: SettingsEmailsNewRoute,
  SettingsEmailsIndexRoute: SettingsEmailsIndexRoute,
}

const SettingsEmailsRouteRouteWithChildren =
  SettingsEmailsRouteRoute._addFileChildren(SettingsEmailsRouteRouteChildren)

interface SettingsRouteRouteChildren {
  SettingsEmailsRouteRoute: typeof SettingsEmailsRouteRouteWithChildren
  SettingsDatabaseRoute: typeof SettingsDatabaseRoute
  SettingsManagementApiRoute: typeof SettingsManagementApiRoute
  SettingsMonitoringRoute: typeof SettingsMonitoringRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsSubscriptionsRoute: typeof SettingsSubscriptionsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsEmailsRouteRoute: SettingsEmailsRouteRouteWithChildren,
  SettingsDatabaseRoute: SettingsDatabaseRoute,
  SettingsManagementApiRoute: SettingsManagementApiRoute,
  SettingsMonitoringRoute: SettingsMonitoringRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsSubscriptionsRoute: SettingsSubscriptionsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface UsersRouteRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NodesRouteRoute: NodesRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvitationsRoute: InvitationsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
